name: video_provider
description: This library enables you to extract mp4 videos from various video providers.
version: 1.2.3+2
homepage: https://github.com/StefanLobbenmeier/video_provider
license: GPL-3.0-or-later

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0